openapi_url: /api/v1/rai/admin/openapi.json
docs_url: /api/v1/rai/admin/docs
title: TrustAI Responsible AI - responsible-ai-admin - OpenAPI 3.0
description: API specs for TrustAI Responsible AI rai_admin pillar in OpenAPI 3.0 format
terms_of_service: https://www.TrustAI.com
contact:
    email: aina@TrustAI.com
license_info:
    name: TrustAI
    url: https://www.TrustAI.com
version: v$version
openapi_tags:
    - name: rai_admin
      description: creating recognizer and account mapping
      externalDocs:
        description: Find out more
        url: https://www.TrustAI.com
