openapi_url: /v1/rai/backend/openapi.json
docs_url: /v1/rai/backend/docs
title: TrustAI Responsible AI - responsible-ai-backend - OpenAPI 3.0
description: API specs for TrustAI Responsible AI rai_backend pillar in OpenAPI 3.0 format
terms_of_service: https://www.TrustAI.com
contact:
    email: aina@TrustAI.com
license_info:
    name: TrustAI
    url: https://www.TrustAI.com
version: v$version
openapi_tags:
    - name: rai_backend
      description: creating users and login management
      externalDocs:
        description: Find out more
        url: https://www.TrustAI.com