openapi_url: /api/v1/privacy/openapi.json
docs_url: /api/v1/privacy/docs
title: TrustAI Responsible AI - responsible-ai-questionnaire - OpenAPI 3.1
description: API specs for TrustAI Responsible AI Privacy pillar in OpenAPI 3.1 format
terms_of_service: https://www.TrustAI.com
contact:
    email: Infosysraitoolkit@TrustAI.com
license_info:
    name: TrustAI
    url: https://www.TrustAI.com
version: v$version
openapi_tags:
    - name: PII Privacy
      description: Operations required for a PII entity (e.g. IN_ADHAAR, IN_PAN, US_SSN etc)
      externalDocs:
        description: Find out more
        url: https://www.TrustAI.com
