openapi_url: /rai/v1/privacy-files/openapi.json
docs_url: /rai/v1/privacy-files/docs
title: TrustAI Responsible AI - responsible-ai-privacy - OpenAPI 3.0
description: API specs for TrustAI Responsible AI Privacy pillar in OpenAPI 3.0 format
terms_of_service: https://www.TrustAI.com
contact:
    email: aina@TrustAI.com
license_info:
    name: TrustAI
    url: https://www.TrustAI.com
version: v$version
openapi_tags:
    - name: PII File Privacy
      description: Operations required for a PII entity (e.g. IN_ADHAAR, IN_PAN, US_SSN etc) from video
      externalDocs:
        description: Find out more
        url: https://www.TrustAI.com
