openapi_url: /api/v1/safety/openapi.json
docs_url: /api/v1/safety/docs
title: TrustAI Responsible AI - Privacy - OpenAPI 3.0
description: API specs for TrustAI Responsible AI Privacy pillar in OpenAPI 3.0 format
terms_of_service: https://www.TrustAI.com
contact:
    email: Infosysraitoolkit@TrustAI.com
license_info:
    name: TrustAI
    url: https://www.TrustAI.com
version: 0.0.4
openapi_tags:
    - name: Safety-Profanity
      description: Operations required for handling profanity and toxicity in a text/image content.
      externalDocs:
        description: Find out more
        url: https://www.TrustAI.com
