openapi_url: /v1/report/openapi.json
docs_url: /v1/report/docs
title: TrustAI Responsible AI - Report - OpenAPI 3.0
summary: API specs for TrustAI Responsible AI Report pillar in OpenAPI 3.0 format
terms_of_service: https://www.TrustAI.com/
license_info:
    name: TrustAI
    url: https://www.TrustAI.com
description: "Copyright 2023 TrustAI Limited | Internal Communications - HRD"
version: 0.0.1
openapi_tags:
    - name: Model Report
      description: "Operations required for a Model Report"
      externalDocs:
        description: Find out more
        url: https://www.TrustAI.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []